import { NavLink, Outlet } from "react-router-dom";
import {
  LayoutDashboard,
  FolderOpen,
  Radio,
  Settings as SettingsIcon,
} from "lucide-react";
import { useHealth } from "../hooks/useHealth";
import { DATA_SOURCE } from "../lib/api";

const NAV = [
  { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { to: "/catalogue", label: "Catalogue", icon: FolderOpen },
];

export function Layout() {
  const { health, ok } = useHealth();

  return (
    <div className="flex h-screen w-screen overflow-hidden bg-bg text-text">
      {/* Sidebar */}
      <aside className="flex w-60 flex-shrink-0 flex-col border-r border-border bg-panel/40">
        <div className="flex items-center gap-3 px-5 pt-5 pb-6">
          <BrandMark />
          <div className="flex flex-col leading-tight">
            <span className="text-[0.78rem] font-bold tracking-[0.22em] brand-grad">
              EGO
            </span>
            <span className="text-[0.7rem] text-text-muted">Ops Dashboard</span>
          </div>
        </div>

        <nav className="flex flex-1 flex-col gap-1 px-3">
          {NAV.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) =>
                [
                  "group flex items-center gap-3 rounded-md px-3 py-2 text-[0.85rem] font-medium transition",
                  isActive
                    ? "border border-accent/40 bg-accent/10 text-accent-hover"
                    : "border border-transparent text-text-muted hover:border-border hover:bg-panel-hover hover:text-text",
                ].join(" ")
              }
            >
              <item.icon size={16} />
              {item.label}
            </NavLink>
          ))}

          <div className="mt-4 px-3 text-[0.6rem] font-semibold uppercase tracking-[0.18em] text-text-dim">
            Stages (soon)
          </div>
          <DisabledNav label="Collection" />
          <DisabledNav label="Postprocessing" />
          <DisabledNav label="Annotation" />
        </nav>

        <div className="mt-auto border-t border-border px-4 py-3 text-[0.7rem] text-text-dim">
          <div className="flex items-center gap-2">
            <span
              className={`inline-block h-1.5 w-1.5 rounded-full ${
                ok ? "bg-ok shadow-[0_0_8px_rgba(34,197,94,0.55)]" : "bg-err"
              }`}
            />
            <span>
              {DATA_SOURCE === "static"
                ? ok
                  ? "Snapshot loaded"
                  : "Snapshot missing"
                : ok
                  ? "Proxy online"
                  : "Proxy offline"}
            </span>
          </div>
          {health && (
            <div className="mt-1 truncate text-[0.62rem] text-text-dim/80">
              {DATA_SOURCE === "static" && health.generated_at
                ? `Snapshot · ${new Date(health.generated_at).toLocaleString()}`
                : health.region}
            </div>
          )}
        </div>
      </aside>

      {/* Content */}
      <div className="flex flex-1 flex-col overflow-hidden">
        <header className="flex h-14 flex-shrink-0 items-center justify-between border-b border-border bg-panel/40 px-6">
          <div className="flex items-center gap-3">
            <span className="text-[0.92rem] font-semibold">
              <span className="brand-grad">Egocentric</span>{" "}
              <span className="font-normal text-text-muted">Production</span>
            </span>
            <span className="rounded-full border border-border bg-input px-2 py-0.5 text-[0.6rem] uppercase tracking-wider text-text-muted">
              v0.1
            </span>
          </div>
          <div className="flex items-center gap-2">
            <div
              className="flex items-center gap-1.5 rounded-md border border-border bg-panel px-2.5 py-1 text-[0.7rem] text-text-muted"
              title={
                DATA_SOURCE === "static"
                  ? "Reading from baked snapshot generated by GitHub Actions"
                  : "Reading from the local Express proxy"
              }
            >
              <Radio size={12} className={ok ? "text-ok" : "text-err"} />
              {DATA_SOURCE === "static"
                ? ok
                  ? "Snapshot"
                  : "Offline"
                : ok
                  ? "Live"
                  : "Disconnected"}
            </div>
            <button className="btn" title="Settings (placeholder)">
              <SettingsIcon size={14} />
            </button>
          </div>
        </header>

        <main className="flex-1 overflow-auto px-6 py-5">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

function DisabledNav({ label }: { label: string }) {
  return (
    <div className="mx-3 flex cursor-not-allowed items-center gap-3 rounded-md px-3 py-2 text-[0.8rem] text-text-dim/80">
      <span className="inline-block h-1.5 w-1.5 rounded-full bg-text-dim/50" />
      {label}
      <span className="ml-auto rounded-full bg-input px-1.5 py-0.5 text-[0.55rem] uppercase tracking-wider text-text-dim">
        soon
      </span>
    </div>
  );
}

function BrandMark() {
  return (
    <div className="relative grid h-8 w-8 place-items-center rounded-md border border-accent/30 bg-panel shadow-glow-accent">
      <span className="absolute inset-0 rounded-md bg-brand-gradient opacity-30 blur-md" />
      <span className="relative h-2 w-2 rounded-full bg-brand-gradient" />
    </div>
  );
}
